apply plugin: 'com.android.application'

android {
    compileSdkVersion 30

    defaultConfig {
        applicationId 'com.ast.breathlessamiga'
        minSdkVersion 16
        targetSdkVersion 28
        versionCode 19
        versionName '0.6.11-teleport-impact-sparks'

        externalNativeBuild {
            cmake {
                cppFlags '-std=c++11 -Wall -Wextra -Wno-unused-parameter'
            }
        }

        ndk {
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
    }

    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
        }
    }
}
